include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for TCPDump
LUCI_DEPENDS:=+tcpdump +libpcap
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-tcpdump
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
